name: CI/CD for Pamoja Pay API

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout code
      - name: Deploy pamoja pay api to the server
        uses: appleboy/ssh-action@master
    
        with:
          host: ${{ secrets.VPS_HOST }}     
          username: ${{ secrets.VPS_USER }}     
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/projects/pamoja/pamojapay_api

            # Set Git credentials
            git config --global credential.helper store
            echo "https://username:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials

            git stash save linuxCommit
            git add *
            git stash
            git pull https://github.com/Pamoja-Pay/pamojapay_api.git main # Update the code on the VPS
            
